import Header from "../../component/Header";
import Footer from "../../component/Footer";
import Head from "next/head";

const PrivacyPolicy = () => {
  return (
    <>
      <Head>
        <title>Terms Of Use</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/gift.svg" />
      </Head>
      <div className="body">
        <Header />
        <div className="main">
          <div className="section">
            <div className="">
              <div className="bg-heading container-fluid"></div>
            </div>
          </div>
          <div className="container privacy-policy-content p-4">
            <h3 className="  privacy-policy-heading">Privacy Policy</h3>
            <div className=" privacy-policy-para py-2">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis
              sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia
              nostra, per inceptos himenaeos. Curabitur sodales ligula in libero.
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
};

export default PrivacyPolicy;
