import Head from "next/head";
import Image from "next/image";
import Header from "../../component/Header";
import Footer from "../../component/Footer";
import Link from "next/link";
import { BiRupee } from "react-icons/bi";
import { BsArrowRightShort, BsArrowRight } from "react-icons/bs";
import { IoMdRefresh } from "react-icons/io";
import { useSelector, useDispatch } from "react-redux";
import { selectResult, selectSearchChat, selectSearchGoogle } from "@/store/slices/searchSlice";
import { useEffect, useState } from "react";
import SearchBar from "../../component/SearchBar";
import SeeMore from '../../component/SeeMore';
import MainLoader from "../../component/MainLoader";

const Search = () => {
  const dispatch = useDispatch();
  const result = useSelector(selectResult);
  const [isLoading, setIsLoading] = useState(false);
  const searchChat = useSelector(selectSearchChat);
  const searchGoogle = useSelector(selectSearchGoogle)

  useEffect(()=>{
    var objDiv = document.getElementById("scroll");
    if(!objDiv)return;   
    objDiv.scrollTop = objDiv.scrollHeight;
  },[searchChat])

  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/gift.svg" />
      </Head>
      {isLoading && <div className='main-loader ' ><MainLoader /> </div>}
      <div className={isLoading?'body opacity-body':'body'}>
        <Header />
        <div className="main">
          <section>
            <div className="">
              <div className="bg-heading-search container-fluid"></div>
            </div>
          </section>e

          <section>
            <div className="container search-section-search-page">
              <div className="col-lg-10 col-md-10 mx-auto">
                <div className="d-flex justify-content-between container ">
                  <p className="search-results">Search Result</p>
                  <Link className="refresh" href="/">
                    <IoMdRefresh className="fa-rotate-right" />
                    Refresh
                  </Link>
                </div>
                <div className="card border-0 main-card">
                  <div className="card-body">
                    <div className="card-text search-input position-relative p-1" id='scroll'>
                    {searchChat.length>1 && searchChat.map((chat,key)=>key!==0 && <div key={key}>{chat.role==='user'?
                        <div className="text-start profile-1-text row position-relative" key={key}>
                          <img src="./assets/user.svg" alt="profile" className="profile1" />
                          <span className=" profile-1-span col-md-6">{chat.content}</span>
                        </div>
                      
                      :
                        <div className="text-end row justify-content-end position-relative profile-2-text" key={key}>
                          <span
                            className="col-md-6 profile-2-span text-start
                         "
                          >
                            {" "}
                             <SeeMore message={chat.content} />
                          </span>
                          <img src="./assets/user.svg" alt="profile" className="profile2" />
                        </div>
                    }</div>)}
                    </div>

                    <hr></hr>
                    <div>
                      {/* <textarea className="w-100 h-100 border-0" placeholder="Continue your search"></textarea>
                      <div className="text-end">
                        <button onClick={()=>handleSearch()} className="search-button btn rounded-0">
                          Search <BsArrowRightShort className="right-arrow"/>
                        </button>
                      </div> */}
                      <SearchBar placeholder="Continue Your Search" isLoading={isLoading} setIsLoading={setIsLoading}/>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

    
            <section className="section-3 container ">
              <div className="col-md-10 mx-auto text-center my-5">
             {result.keywords &&  <Link className="btn btn-outline-danger product-button" href={`https://www.amazon.com/s?k=${result.keywords.slice(0,5).join('+')}`} target='_blank'>Here are some Product ideas for you</Link>
}</div>
         
            </section>
          
        </div>
        <Footer />
      </div>
    </>
  );
};
export default Search;
